name: Backend & Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests (placeholder)
        run: echo "Replace with real tests (npm test / pytest etc.)"

  build_and_push:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push product-service
        uses: docker/build-push-action@v6
        with:
          context: ./backend/product_service
          file:    ./backend/product_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/product-service:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/product-service:${{ github.sha }}

      - name: Build & push order-service
        uses: docker/build-push-action@v6
        with:
          context: ./backend/order_service
          file:    ./backend/order_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/order-service:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file:    ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
